apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/node-selector: ""
    openshift.io/sa.initialized-roles: "true"
    openshift.io/description: ""
  name: collectd
spec:
  finalizers:
  - kubernetes
  - openshift.io/origin
~                             
