apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: collectd
  labels:
    name: collectd
spec:
  template:
    metadata:
      labels:
        name: collectd
    spec:
      hostNetwork: true
      containers:
      - image: collectd
        name: collectd
        imagePullPolicy: "IfNotPresent"
        securityContext:
          privileged: true
        volumeMounts:
          - name: proc-mount
            mountPath: /proc_host
        ports:
          - containerPort: 2222
      volumes:
        - name: proc-mount
          hostPath:
            path: /proc
      nodeSelector: 
        type: collectd
      volumes:
        - name: config-volume
          configMap:
            name: collectd-config-map
